---
title: "Generative Art Lab"
author: "Chloe Feehan"
format: 
  html: 
    self-contained: true
    code-tools: true
    code-fold: true
    embed-resources: true
editor: visual
execute: 
  echo: true
  include: true
  message: false
  warning: false
---

```{r}
#| label: libraries

library(ggplot2)
library(scales)
library(ggthemes)
library(tibble)
```

```{r}
set.seed(1)
n <- 50
dat <- tibble(
  x0 = runif(n),
  y0 = runif(n),
  x1 = x0 + runif(n, min = -.2, max = .2),
  y1 = y0 + runif(n, min = -.2, max = .2),
  shade = runif(n), 
  size = runif(n)
)


pal <- c("darkslategray3", "aquamarine4", "cadetblue", "lightblue")


dat |>
  ggplot(aes(x = x0, y = y0,
             xend = x1, yend = y1,
             color = x0)) +
  geom_segment(show.legend = FALSE, linewidth = 30) +
  geom_point(show.legend = FALSE, size = 15, shape = 17, 
             color = "green4") +
  geom_point(show.legend = FALSE, size = 10, shape = 17, 
             color = "springgreen3") +
  geom_point(show.legend = FALSE, size = 6, shape = 17, 
             color = "lightgreen") +
  
  #coord_polar() +
  scale_y_continuous(expand = c(0, 0)) +
  scale_x_continuous(expand = c(0, 0)) + 
  scale_colour_gradientn(colours = pal) +
  scale_size(range = c(0, 10)) +
  theme_void() +
  labs(title = "Forest") +
  theme(
    plot.title = element_text(family = "Times New Roman", size = 20, 
                              face = "italic", color = "black")
  )
```

```{r}



# Define the number of points and the Golden Angle
points <- 300
angle <- pi * (3 - sqrt(5))

# Generate the spiral points
t <- (1:points) * angle
x <- sin(t)
y <- cos(t)
df <- data.frame(t, x, y)

# Plot the points in a spiral pattern
p <- ggplot(df, aes(x * t, y * t, color = t))

# Create a flower-like plot
p + geom_point(aes(size = t), alpha = 0.8, shape = 16) +
  scale_color_gradient(low = "yellow", high = "red") +  
  scale_size(range = c(1, 9)) +  # 
  theme(panel.background = element_rect(fill = "white"),
        panel.grid = element_blank(),
        axis.text = element_blank(),
        axis.title = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "none") +
  ggtitle("Flower-like Spiral Plot")



# source: https://art-from-code.netlify.app/day-1/session-3/
# source: https://rpubs.com/Sergio_Garcia/phyllotaxis_r
# source: https://ggplot2.tidyverse.org/reference/scale_gradient.html 

```
